import "./WeddingGallery.css";

import {
  IonButton,
  IonCol,
  IonContent,
  IonGrid,
  IonImg,
  IonRow,
  IonSlide,
  IonSlides,
  IonText,
} from "@ionic/react";

// Optional parameters to pass to the swiper instance.
// See http://idangero.us/swiper/api/ for valid options.
const slideOpts = {
  initialSlide: 0,
  speed: 400,
  loop: true,
  autoplay: {
    delay: 4000,
  },
};

export const VuQuyGallery: React.FC = () => (
  <IonContent>
    <IonSlides options={slideOpts}>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/1_wYgLzwScD.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186076445`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/2_uXRYCO4LUBy.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186075062`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/3_PV_N47Cf4.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186067837`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/4_TjAqsIFnvG2.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642185734429`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/5_DTm-iKXYQ.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642185735446`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/6_Ij-pXe2YG.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642185735552`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/7_rcvXuW5-p.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186069044`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/8_i0F6wQb8Q.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642185736268`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/9_HPG21J7HlFE.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186065213`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/10_YPnVC_2NV.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186065185`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/11_HqOKpCtek.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186065675`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/12_T0S0sf6gq.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186423532`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/13_tMjAWThvh.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186421988`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/14_nKmt4Che3X-.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186419988`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/15_jls7BtOdr.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186419760`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/16_34ZQOJWgs79.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186423836`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/17_CzkjH0irr0.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186422773`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/18_bdbhWnQXK.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186426049`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/19_ZyK-R7dP3sF.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186427568`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonGrid>
          <IonRow>
            <IonCol>
              <IonImg
                src={`https://ik.imagekit.io/namlinhfamily/vuquy/20_kRwpSovab.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642186422329`}
              ></IonImg>
            </IonCol>
          </IonRow>
        </IonGrid>
      </IonSlide>
      <IonSlide>
        <IonButton routerLink="/prewedding">Xem hình Prewedding</IonButton>
      </IonSlide>
    </IonSlides>
  </IonContent>
);
